---
- name: install HTTP server
  hosts: n3
  become: yes

  tasks:
    - name: install HTTPD
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon"

    - name: start httpd
      service:
        name: httpd
        state: started
        when: ansible_distribution == "Amazon"

    - name: enable HTTPD
      service:
        name: httpd
        enabled: yes
        when: ansible_distribution == "Amazon"

  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: start apache2
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"

    - name: enable Apache2
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == "Ubuntu"
       
...
