---
- name: Under maintenance
  hosts: n1
  become: yes

  tasks:
    - name: Update maintenance
      copy:
        src: variablefile.html
        dest: /var/www/html/index.html/variablefile.html

...